In [109]:
import random
import numpy as np

In [110]:
random.seed(4)
np.random.seed(4)

The matrix will be generated with dimentions n and m both between 1 and 10, to facilitate visualization and analisys. Also, the values of the matrix will be random numbers between 0 and 50

In [111]:
n = random.randint(1,10)
m = random.randint(1,10)

In [112]:
print(f"The matrix will be generated with the dimentions mxn with m = {m} and n = {n}")

The matrix will be generated with the dimentions mxn with m = 5 and n = 4


In [113]:
A_rectangular = np.random.randint(0,50,(n,m))
print('Rectangular Matrix Ar:\n')
print(A_rectangular)

Rectangular Matrix Ar:

[[46  5  1 40 23]
 [ 8  9 39 45 30]
 [40 36 44 38 42]
 [ 3  0 21 21  9]]


In [114]:
rank_A = np.linalg.matrix_rank(A_rectangular)
print("Rank of the rectangular matrix Ar:", rank_A)

Rank of the rectangular matrix Ar: 4


It's important to know the rank of a matrix since this value provides a lot of important information about the matrix itself and its properties. With this rank value we can obtain the following information:

- In this matrix there are 4 linearly independent rows 

- The nullity of a matrix can be calculated as the difference between the number of columns and the rank of the matrix. In the case of this matrix with rank 4 and 5 columns the nullity is 1, and there is only one linearly independent solution to the equation Ax = 0.

- A square matrix is invertible if and only if its rank is equal to its dimension. In this case A is rectangular, however, later it will be demonstrated that the square submatrix of A is invertible

In [115]:
trace_A = np.trace(A_rectangular)
print("Trace of the rectangular matrix Ar:", trace_A)

Trace of the rectangular matrix Ar: 120


Since non-square matrices do not have determinants we are going to select only n rows (with n<m) from the previous matrix

In [116]:
A = A_rectangular[0:n,0:n]
print('Matrix A:\n')
print(A)

Matrix A:

[[46  5  1 40]
 [ 8  9 39 45]
 [40 36 44 38]
 [ 3  0 21 21]]


In [117]:
det_A = np.linalg.det(A)
print('Determinant of the matrix A:',det_A)

Determinant of the matrix A: 414143.9999999995


We can say that this matrix is invertible since the determinant is not equal to zero and is a square matrix

There are several methods to invert a matrix, including:

- Gaussian elimination: this method involves transforming the matrix into row echelon form and then using back substitution to obtain the inverse. It is computationally expensive for large matrices.

- LU decomposition: this method involves decomposing the matrix into a lower triangular matrix and an upper triangular matrix, and then using these matrices to obtain the inverse. It is faster than Gaussian elimination and can be used for large matrices.

- QR decomposition: this method involves decomposing the matrix into an orthogonal matrix and an upper triangular matrix, and then using these matrices to obtain the inverse. It is also faster than Gaussian elimination and can be used for large matrices.

- Singular value decomposition (SVD): this method involves decomposing the matrix into three matrices, and then using these matrices to obtain the inverse. It is a more robust method and can be used for matrices that are ill-conditioned or singular.

The function numpy.linalg.inv uses the LU decomposition method to compute the inverse of a matrix. 

In [118]:
A_inv = np.linalg.inv(A)
print('Inverse of the matrix A:\n')
print(A_inv)

Inverse of the matrix A:

[[ 0.01369089 -0.07271384  0.01627695  0.10028396]
 [-0.01099618  0.08062413  0.00914899 -0.16837622]
 [-0.01290855 -0.06477457  0.0179865   0.13084338]
 [ 0.01095271  0.07516226 -0.02031178 -0.09755061]]


First we are going to calculate the transpose of matrix A

In [119]:
At = A.transpose()
print("At = A':")
print(At)

At = A':
[[46  8 40  3]
 [ 5  9 36  0]
 [ 1 39 44 21]
 [40 45 38 21]]


In [141]:
AtA = np.matmul(At,A)
print("A'A:")
print(At_A)

A'A:
[[3789 1742 2181 3783]
 [1742 1402 1940 1973]
 [2181 1940 3899 3908]
 [3783 1973 3908 5510]]


In [142]:
AAt = np.matmul(A,At)
print("AA':")
print(A_At)

AA':
[[3742 2252 3584  999]
 [2252 3691 4070 1788]
 [3584 4070 6276 1842]
 [ 999 1788 1842  891]]


In [143]:
eig_vals_AtA,eig_vecs_AtA = np.linalg.eig(AtA)

In [144]:
eig_vals_AAt,eig_vecs_AAt = np.linalg.eig(AAt)

In [145]:
eig_vals_AtA

array([1.21913505e+04, 1.67008481e+03, 1.15875506e+01, 7.26977155e+02])

In [146]:
eig_vecs_AtA

array([[ 0.48505484,  0.72239504,  0.42209915, -0.25436099],
       [ 0.28847657, -0.07728663, -0.6308016 , -0.71616854],
       [ 0.50341182, -0.68662419,  0.49874273, -0.16241753],
       [ 0.65427793,  0.02682179, -0.41854192,  0.6293041 ]])

In [147]:
eig_vals_AAt

array([1.21913505e+04, 1.67008481e+03, 7.26977155e+02, 1.15875506e+01])

In [148]:
eig_vecs_AAt

array([[-0.45672858, -0.81313171,  0.36080827,  0.0057634 ],
       [-0.50312524,  0.5013323 ,  0.50084335, -0.49465833],
       [-0.69556143,  0.07533653, -0.71170377,  0.06321745],
       [-0.23336302,  0.28601951,  0.33533724,  0.8667661 ]])

The eigenvalues and eigenvectors of A’A and AA’ are related as follows:

- The eigenvalues of A’A and AA’ are the same, and the eigenvectors are related by the matrix A and its transpose A’.
- If v is an eigenvector of A’A corresponding to an eigenvalue λ, then Av is an eigenvector of AA’ corresponding to the same eigenvalue λ.
- If u is an eigenvector of AA’ corresponding to an eigenvalue μ, then A’u is an eigenvector of A’A corresponding to the same eigenvalue μ.


In [159]:
np.matmul(A,eig_vecs_AtA[:,0])/np.linalg.norm(np.matmul(A,eig_vecs_AtA[:,0]))

array([0.45672858, 0.50312524, 0.69556143, 0.23336302])

In [160]:
np.matmul(At,eig_vecs_AAt[:,0])/np.linalg.norm(np.matmul(At,eig_vecs_AAt[:,0]))

array([-0.48505484, -0.28847657, -0.50341182, -0.65427793])